theme: jekyll-theme-cayman
title: 3D Computer Vision in Medical Environments
description: in conjunction with CVPR 2019
body .tablelines table, 
body .tablelines td, 
body .tablelines th {
    border: none; padding:10px;
}
